# SPDX-FileCopyrightText: 2026 Goethe-University Frankfurt – Institute for Digital Medicine and Clinical Data Science
# SPDX-FileCopyrightText: 2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---

- name: Restart authelia
  ansible.builtin.systemd:
    name: authelia
    state: restarted
    daemon_reload: true
  listen: restart authelia

- name: Reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
  listen: reload caddy
