# SPDX-FileCopyrightText: 2024 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2024 Tom-Robin Raja <tom-robin.raja@uk-koeln.de>
# SPDX-FileCopyrightText: 2024 Uniklinik Köln
# SPDX-FileCopyrightText: 2025 Goethe-University Frankfurt – Institute for Digital Medicine and Clinical Data Science
# SPDX-FileCopyrightText: 2025 Vasilii Tulskii <tulskyva@mail.ru>
#
# SPDX-License-Identifier: Apache-2.0 OR EUPL-1.2

---

- name: caddy vhosts for the list domains
  template:
    src: caddy-vhost.j2
    dest: "{{ sympa_caddy_conf_dir }}/{{ virtual_domain }}"
    owner: root
    group: caddy
    mode: "0640"
  loop: "{{ sympa_domains | union([sympa_main_domain]) }}"
  loop_control:
    loop_var: virtual_domain
  notify: reload caddy
  when: sympa_configure_caddy

- name: Ensure wwsympa systemd socket is started and enabled
  systemd:
    name: wwsympa.socket
    enabled: yes
    state: started
