#!/usr/bin/python3

# SPDX-FileCopyrightText: 2016 - 2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2020 - 2025 Uniklinik Köln
# SPDX-FileCopyrightText: 2025 - 2026 Goethe-University Frankfurt – Institute for Digital Medicine and Clinical Data Science
#
# SPDX-License-Identifier: EUPL-1.2

# Ask a VM to power down gracefully over its QMP socket. systemd's
# TimeoutStopSec is the backstop for guests that ignore ACPI.

import json
import socket
import sys

sock = socket.socket(socket.AF_UNIX)
sock.connect(sys.argv[1])
qmp = sock.makefile("rw")
qmp.readline()  # greeting
for command in ("qmp_capabilities", "system_powerdown"):
    qmp.write(json.dumps({"execute": command}) + "\n")
    qmp.flush()
    qmp.readline()
